import taskmanager.managers.*;
import taskmanager.tasks.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


import static org.junit.jupiter.api.Assertions.*;

class InMemoryTaskManagerTest extends TaskManagerTest<InMemoryTaskManager> {

    @Override
    protected  InMemoryTaskManager createTaskManager() {
        return new InMemoryTaskManager();
    }


    @Test
    void correctCountId() {
        assertEquals(6, getTaskManager().getCountId());
    }

    @Test
    void tasksWithSameId() {
        Task task3 = new Task("Задача 1", "ДЗ 1", Status.NEW, TaskType.MIDDLE_TASK);
        Task task4 = new Task("Задача 2", "ДЗ 2", Status.IN_PROGRESS, TaskType.MIDDLE_TASK);
        task3.setId(1);
        task4.setId(1);
        assertTrue(task3.equals(task4));
    }

    @Test
    void heirsTasksWithSameId() {
        epic1 = new Epic("Эпик 1", "ДЗ 1", Status.NEW, TaskType.EPIC, new ArrayList<>());
        epic2 = new Epic("Эпик 2", "ДЗ 2", Status.NEW, TaskType.EPIC, new ArrayList<>());
        subtask1 = new Subtask("Субзадача 1", "ДЗ 1", Status.NEW, TaskType.SUBTASK, epic1.getId(), LocalDateTime.now(), Duration.ofMinutes(10));
        subtask2 = new Subtask("Субзадача 2", "ДЗ 2", Status.NEW, TaskType.SUBTASK, epic2.getId(), LocalDateTime.now().plusMinutes(20), Duration.ofMinutes(10));
        epic1.setId(1);
        epic2.setId(1);
        subtask1.setId(1);
        subtask2.setId(1);

        assertTrue(subtask1.equals(subtask2));
        assertTrue(epic1.equals(epic2));
        assertFalse(epic1.equals(subtask1));
    }


    @Test
    void manualAndAutoGeneratedIdsShouldNotConflict() {
        Task task3 = new Task("Задача 1", "ДЗ 1", Status.NEW, TaskType.MIDDLE_TASK);
        task3.setId(500);
        getTaskManager().updateTask(task3);

        assertNotEquals(task3.getId(), task1.getId());
        assertNotNull(getTaskManager().getTaskById(task1.getId()));
        assertNotNull(getTaskManager().getTaskById(task3.getId()));
    }







}